services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: example_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - redis
        networks:
            - example_network

    nginx:
        image: nginx:latest
        container_name: example_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - example_network

    redis:
        image: redis:latest
        container_name: example_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - example_network

    db:
        image: mysql:8.0
        container_name: example_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: example
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - example_network

networks:
    example_network:
        driver: bridge

volumes:
    mysql_data:
    redis_data:
